/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 31 15:56:08 GMT 2026
 */

package org.apache.openjpa.lib.util.evo.regex;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.openjpa.lib.util.SimpleRegex;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class SimpleRegex_ESTest extends SimpleRegex_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SimpleRegex simpleRegex0 = new SimpleRegex("qC.*", true);
      boolean boolean0 = simpleRegex0.matches("Rt=j");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimpleRegex simpleRegex0 = new SimpleRegex("eXt|VDFWa(jG", true);
      boolean boolean0 = simpleRegex0.matches("5bo`q<=g<>.");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SimpleRegex simpleRegex0 = new SimpleRegex(".U*", true);
      boolean boolean0 = simpleRegex0.matches(".U*");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SimpleRegex simpleRegex0 = new SimpleRegex("qC.*", false);
      boolean boolean0 = simpleRegex0.matches("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SimpleRegex simpleRegex0 = new SimpleRegex(".**", false);
      boolean boolean0 = simpleRegex0.matches("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SimpleRegex simpleRegex0 = new SimpleRegex("eXt|VDFWa(jG", true);
      boolean boolean0 = simpleRegex0.matches("FlEY}+!I;j[E_");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SimpleRegex simpleRegex0 = new SimpleRegex("qC.*", false);
      boolean boolean0 = simpleRegex0.matches("qC.*");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SimpleRegex simpleRegex0 = new SimpleRegex(".*", true);
      boolean boolean0 = simpleRegex0.matches("eXt|VDFWa(jG");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      SimpleRegex simpleRegex0 = new SimpleRegex("o17.O?Jhg=", true);
      boolean boolean0 = simpleRegex0.matches("@Y_L_3?$v");
      assertFalse(boolean0);
  }
}
