name: Java CI with Maven

on:
  push:
    branches: [ "3.2.x-Reduced_And_No_Test_Version"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Test and run Jacoco
      run: mvn clean test -pl openjpa-lib -Pcoverage
    - name : Test and run Pit
      run: mvn clean test org.pitest:pitest-maven:mutationCoverage -pl openjpa-lib -Ppit
